
version: '3'
services:
  flask: 
    image: flask_app-flask:latest
    deploy:
      replicas: 2
    env_file: ./.env
    volumes:
      - flask_conf:/var/www/html/flask
    
    networks:
      - flask-net
      
networks:
  flask-net:
   external: true

volumes:
  flask_conf:
   external: true